language: python

# cache pip dependency
cache: pip

sudo: required

jobs:
    include:
        - python: "2.7"
          install:
              - pip install -r requirements.txt
          script:
              - sudo env "PATH=$PATH" python --version          # environment check
              - sudo env "PATH=$PATH" python -c 'import psutil' # ensure deps are installed.

              # Some tests do not pass on travis-ci.
              # E.g.: redis, mysql, zookeeper, etcd needs a docker to test.
              # Disable them temporarily.
              # -- by xp 2020 Jan 27


              # Enable debug log: UT_DEBUG=1
              - >-
                  sudo env "PATH=$PATH"
                  UT_DEBUG=1
                  PYTHONPATH="$(cd ..; pwd)"
                  python -m unittest
                  -c
                  -v
                  --failfast
                  "pykit.http.test.test_httpclient.TestHttpClient.test_set_timeout"
                  sudo env "PATH=$PATH" ./script/run-test
                  http

# after_success:
#   - pip install python-coveralls && coveralls
