#!/bin/sh

allpkgs="$(find . -mindepth 2 -maxdepth 2 -name "__init__.py" | awk -F/ '{print $2}')"

for pkg in $allpkgs; do
    { echo "$@" | grep -q "\b$pkg\b"; } || echo "Not tested: $pkg"
done

for pkg in "$@"; do

    echo "=== Test $pkg ==="

    UT_DEBUG=1                     \
        PYTHONPATH="$(cd ..; pwd)" \
        python -m unittest         \
        discover                   \
        -c                         \
        -v                         \
        -s                         \
        --failfast                 \
        "pykit.$pkg"               \
        || exit 1
done
